### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by benjamine** [AtomLinter/Linter#386] opened 2015-01-23 15:43 UTC
[Enter steps to reproduce below:]

1. opened atom, on a js project folder (a js file opened)

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJscs.Linter.getNodeExecutablePath (/Users/benja/.atom/packages/linter/lib/linter.coffee:104:10)
  at LinterJscs.Linter.getCmdAndArgs (/Users/benja/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJscs.Linter.lintFile (/Users/benja/.atom/packages/linter/lib/linter.coffee:112:24)
  at /Users/benja/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/benja/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "linter": {
    "showErrorInline": true,
    "statusBar": "Show all errors"
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, vundefined
autoclose-html, v0.13.0
autocomplete-plus, v1.0.0
csslint, v0.5.1
editor-stats, v0.16.0
highlight-selected, v0.7.0
linter, v0.9.0
linter-csslint, v0.0.11
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-less, v0.3.1
max-tabs, v0.3.0
minimap, v3.4.9
minimap-highlight-selected, v3.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-24 18:53
Closing as dupe of #329. This is fixed in the latest version; please upgrade!

**Closed by dmnd** 2015-01-24 18:53 UTC
