### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by revspringjake** [AtomLinter/Linter#400] opened 2015-01-30 20:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/jakedanforth/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/jakedanforth/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (/Users/jakedanforth/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/jakedanforth/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/jakedanforth/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "relative-numbers",
      "welcome"
    ],
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
color-picker, v1.2.6
highlight-selected, v0.7.0
linter, v0.9.1
linter-jshint, v0.1.0
monokai, v0.9.0
unity-ui, v1.0.7
vim-mode, v0.26.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-30 20:23
Closing as dupe of #329. This is already fixed, please upgrade! :smile:

**Closed by dmnd** 2015-01-30 20:23 UTC
