### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by ameyms** [AtomLinter/Linter#394] opened 2015-01-27 00:13 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/amey_sakhadeo/.atom/packages/linter/lib/linter.coffee:104:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/amey_sakhadeo/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJshint.Linter.lintFile (/Users/amey_sakhadeo/.atom/packages/linter/lib/linter.coffee:112:24)
  at /Users/amey_sakhadeo/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/amey_sakhadeo/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "fizzy"
    ]
  },
  "linter": {
    "lintOnChange": false,
    "showErrorInline": true,
    "statusBar": "Show error if the cursor is in range"
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.4.3
fizzy, v0.15.0
linter, v0.9.0
linter-clang, v2.9.0
linter-flake8, v1.2.0
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-pep8, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-30 08:33
Dupe of #329. This is fixed, please upgrade your linter package.

**Closed by dmnd** 2015-01-30 08:33 UTC
