### ISSUE TITLE
Option to exclude certain types of files

### ISSUE THREAD

**Issue by spudly** [AtomLinter/Linter#549] opened 2015-05-29 19:47 UTC
For debugging purposes, I sometimes pull up a file that is concatenated and uglified. When I do so, atom tries to lint the entire thing and just hangs (understandably). I then have to force-close atom and reopen it.

It sure would be nice if I could explicitly exclude minified files from linter so that atom doesn't waste cycles trying to lint something that doesn't even need to be linted.

I'd be happy with either a regex or a glob, as long as I can specify that it should exclude "*.min.*" (my minified always end with .min.js)

**Comment by steelbrain** [comment] 2015-05-29 19:48
Dupe of #519

**Closed by steelbrain** 2015-05-29 19:48 UTC

**Comment by spudly** [comment] 2015-05-29 19:49
Sorry, didn't find that one when searching issues. Should have searched for 'ignore' instead of 'exclude' I guess.
