### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by paul5** [AtomLinter/Linter#573] opened 2015-06-23 14:03 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.0.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At module.js:330

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterJsonlint.Linter.getEditorScopesForPosition (/Users/paul/.atom/packages/linter/lib/linter.coffee:291:31)
  at LinterJsonlint.Linter.computeRange (/Users/paul/.atom/packages/linter/lib/linter.coffee:337:5)
  at LinterJsonlint.Linter.createMessage (/Users/paul/.atom/packages/linter/lib/linter.coffee:16:3)
  at LinterJsonlint.<anonymous> (/Users/paul/.atom/packages/linter/lib/linter.coffee:235:37)
  at Function.self.forEach (/Users/paul/.atom/packages/linter/node_modules/xregexp/xregexp-all.js:542:22)
  at LinterJsonlint.Linter.processMessage (/Users/paul/.atom/packages/linter/lib/linter.coffee:236:7)
  at /Users/paul/.atom/packages/linter/lib/linter.coffee:165:7
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  6x -1:16.4.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:15.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:12.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:11.8.0 core:move-up (atom-text-editor.editor.is-focused)
  6x -1:04.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.5.0 core:cut (atom-text-editor.editor.is-focused)
     -0:58.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:35.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:27.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:25.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:24.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:21.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.3.0 core:paste (atom-text-editor.editor.is-focused)
  6x -0:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "dracula-theme"
    ],
    "disabledPackages": [
      "atom-lint"
    ]
  },
  "linter": {
    "ignoredLinterErrors": [
      "jshint",
      "chktex",
      "pylint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.7
colorful-json, v1.0.0
dracula-theme, v0.7.6
file-icons, v1.5.7
language-latex, v0.6.1
latex, v0.24.2
linter, v1.0.0
linter-chktex, v0.3.0
linter-jshint, v0.1.6
linter-jsonlint, v0.1.4
linter-pylint, v0.2.2
minimap, v4.10.0
pdf-view, v0.22.0
pretty-json, v0.3.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-06-23 14:04
Dupe of #572

**Closed by steelbrain** 2015-06-23 14:04 UTC
