### ISSUE TITLE
Linter message panel leaves behind padding when switching to a tab without linter errors

### ISSUE THREAD

**Issue by mnquintana** [AtomLinter/Linter#690] opened 2015-07-04 01:11 UTC
Steps to reproduce:

1. Open a file with a linter error.
1. Switch to a file with no linter errors or a non-editor tab.
1. There will be extra padding on top of the status bar.

### Expected
<img width="689" alt="screenshot 2015-07-03 21 10 07" src="https://cloud.githubusercontent.com/assets/823545/8505928/f16489be-21c7-11e5-8039-a5039b8cfec3.png">

### Actual
<img width="689" alt="screenshot 2015-07-03 21 09 51" src="https://cloud.githubusercontent.com/assets/823545/8505929/f80f1568-21c7-11e5-9b26-90f0d0f27489.png">

**Comment by steelbrain** [comment] 2015-07-04 01:11
Can you repro this bug on https://github.com/AtomLinter/Linter/pull/664

**Comment by mnquintana** [comment] 2015-07-04 01:16
I can if I enable `Show Error Panel at the bottom`.

**Comment by steelbrain** [comment] 2015-07-04 01:19
Ah, I think I know what the problem is, that status icon shows errors from Project scope even when you disable the tab.
Maybe we could show errors from the selected scope there?
/cc @AtomLinter/linter

**Comment by steelbrain** [comment] 2015-07-05 17:25
Dupe of #683

**Closed by steelbrain** 2015-07-05 17:25 UTC
Labels: enhancement, ui
