### ISSUE TITLE
Reduce emphasis on status bar error message for clean files

### ISSUE THREAD

**Issue by eboracus** [AtomLinter/Linter#724] opened 2015-07-09 23:41 UTC
Superficial improvement request: It would be nice to have the red 'Issue' message on the status bar be dimmed or reduced in emphasis when viewing a file that doesn't contain any of the issues in the current project. So the emphasis would alternate in the example below, lower when on the file with no errors and higher on the other.

![lint_file_project](https://cloud.githubusercontent.com/assets/11758299/8609327/b5b899b8-269b-11e5-9caf-d0a771202c51.gif)

It really stands out (as it should do :) ) and has made me think at a glance a few times that there are errors in the current file, that I thought was (and is) ok.

**Comment by steelbrain** [comment] 2015-07-10 19:01
We have it planned to allow user to select the scope of it. Dupe of https://github.com/AtomLinter/Linter/issues/683

**Closed by steelbrain** 2015-07-10 19:01 UTC
Labels: enhancement, ui
