### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by dustinmoorenet** [AtomLinter/Linter#340] opened 2015-01-15 18:31 UTC
Steps to reproduce:

1. Open atom in folder with tabs already open

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/dustin/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/dustin/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (/Users/dustin/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/dustin/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/dustin/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus"
    ],
    "projectHome": "/Users/dustin/dev"
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
js-refactor, v0.3.0
linter, v0.9.1
linter-jshint, v0.1.0
refactor, v0.4.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-15 18:41
Dupe of #329. This is fixed in the latest version; please upgrade!

**Closed by dmnd** 2015-01-15 18:41 UTC
