### ISSUE TITLE
Failed to activate package named 'linter' TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Stephen304** [AtomLinter/Linter#396] opened 2015-01-29 04:31 UTC
I've been wondering why my linters haven't been linting, and I finally got the console open and noticed this. I uninstalled all linter plugins and reinstalled the base plugin and a couple linters again. This is the error I get every time (replace csslint with any linter name, its the same error no matter which linter it is).

I made sure the package folders were gone from .atom/packages/

    Failed to activate package named 'linter' TypeError: undefined is not a function
      at LinterCsslint.Linter (/home/stephen/.atom/packages/linter/lib/linter.coffee:54:33)
      at new LinterCsslint (/home/stephen/.atom/packages/linter-csslint/lib/linter-csslint.coffee:28:5)
      at LinterView.initLinters (/home/stephen/.atom/packages/linter/lib/linter-view.coffee:51:27)
      at new LinterView (/home/stephen/.atom/packages/linter/lib/linter-view.coffee:33:6)
      at /home/stephen/.atom/packages/linter/lib/init.coffee:83:24
      at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:268:9)
      at LinterInitializer.activate (/home/stephen/.atom/packages/linter/lib/init.coffee:80:39)
      at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:225:27)
      at /usr/share/atom/resources/app/src/package.js:211:28
      at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:157:15)
      at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:205:14)
      at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
      at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:234:29
      at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
      at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
      at /usr/share/atom/resources/app/src/buffered-process.js:70:18
      at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
      at Socket.emit (events.js:129:20)
      at Pipe.close (net.js:461:12)

Any ideas?

**Comment by dmnd** [comment] 2015-01-30 08:32
Closing as dupe of #389. 

To fix this, upgrade your version of Atom.

**Closed by dmnd** 2015-01-30 08:32 UTC
