### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by McLeanBH** [AtomLinter/Linter#384] opened 2015-01-22 20:26 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
StatusBarSummaryView.render (/Users/Bennett_McL/.atom/packages/linter/lib/statusbar-summary-view.coffee:11:21)
```

Two days ago I first noticed that in the bottom right pane of Atom, there was a new notification: an orange triangle with an exclamation point in the middle. This alert notified me that I have the six deprecated calls, which are listed below. All packages are up-to-date. I have been using Atom for only about three weeks, but these deprecations have only been present for the past several days. I do not know what has changed. Please advise. Thank you- Ben

-- html-entities (2 deprecations)
(1) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time, Create Issue on html-entities repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> Object.activate - /Users/Bennett_McL/.atom/packages/html-entities/lib/html-entities.coffee:5:9

(2) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time, Create Issue on html-entities repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> Object.activate - /Users/Bennett_McL/.atom/packages/html-entities/lib/html-entities.coffee:8:9

-- linkify (1 deprecation)
(1) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time, Create Issue on linkify repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> Object.activate - /Users/Bennett_McL/.atom/packages/linkify/lib/linkify.coffee:5:9

-- linter (1 deprecation)
(1) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 898 times, Create Issue on linter repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> StatusBarSummaryView.render - /Users/Bennett_McL/.atom/packages/linter/lib/statusbar-summary-view.coffee:11:21

-- tag (2 deprecations)
(1) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time, Create Issue on tag repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> Object.activate - /Users/Bennett_McL/.atom/packages/tag/lib/tag.js:11:9

(2) atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time, Create Issue on tag repo
-> Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
-> Object.activate - /Users/Bennett_McL/.atom/packages/tag/lib/tag.js:17:16

**Comment by dmnd** [comment] 2015-01-22 20:28
Closing as dupe of #343 

This is fixed in the latest version of linter.

**Closed by dmnd** 2015-01-22 20:28 UTC
