### ISSUE TITLE
Error panel covers the entire screen (doesn't have a proper max size)

### ISSUE THREAD

**Issue by mc10** [AtomLinter/Linter#723] opened 2015-07-09 17:42 UTC
For an file that has a lot of errors (maybe because I accidentally removed a quote mark), Linter fills up the error screen to cover the *entire* window, making it impossible to even edit the file and remove the error. The only solution is either to undo the change or disable the use of the error panel.

**Comment by steelbrain** [comment] 2015-07-09 17:52
It's actually an error in your theme :)

**Comment by steelbrain** [comment] 2015-07-09 19:30
Closing as invalid. Feel free to continue the discussion.

**Closed by steelbrain** 2015-07-09 19:30 UTC

**Comment by mc10** [comment] 2015-07-09 19:43
Uh I'm using the default theme, One Dark, so if that's broken...

**Comment by steelbrain** [comment] 2015-07-09 19:44
I am unable to reproduce this error on the same theme :)
For me, it's max-height works. What's your atom version?

**Comment by mc10** [comment] 2015-07-09 19:45
v1.0.2.

![Screenshot of the issue](https://i.imgur.com/BZIV0WM.png)
