### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by tiagonbotelho** [AtomLinter/Linter#296] opened 2014-12-16 18:04 UTC
Uncaught Error: spawn ENOTDIR

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At child_process.js:1160

Error: spawn ENOTDIR
  at exports._errnoException (util.js:742:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:47:37)
  at LinterPylint.Linter.lintFile (/Users/tiagobotelho/.atom/packages/linter/lib/linter.coffee:142:19)
  at /Users/tiagobotelho/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/tiagobotelho/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-12 05:34
Closing this it's basically a dupe of #150

**Closed by dmnd** 2015-01-12 05:34 UTC
