### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by scashin133** [AtomLinter/Linter#341] opened 2015-01-15 18:33 UTC
[Enter steps to reproduce below:]

I have no idea what actually caused this so I'll just try to accurately describe the state of atom from my perspective when I got this exception.

1. Atom was already running but had no windows open.
2. I opened my rails project from the command line using `atom .`
2. When atom loaded about 15 previously opened tabs were already open and the active one was a non saved empty tab.

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/scashin133/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/scashin133/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (/Users/scashin133/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/scashin133/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/scashin133/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-soda-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-soda-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "linter": {
    "showHighlighting": false,
    "showErrorInline": true
  }
}
```

### Installed Packages

```coffee
# User
atom-soda-dark-ui, v0.8.0
git-tab-status, v1.3.0
html2haml, v0.6.0
jsformat, v0.7.18
language-javascript-semantic, v0.1.0
linter, v0.9.1
linter-coffeelint, v0.1.7
linter-handlebars, v0.1.1
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-rubocop, v0.2.1
linter-scss-lint, v0.0.11
pretty-json, v0.3.1
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-15 18:41
Dupe of #329. This is fixed in the latest version; please upgrade!

**Closed by dmnd** 2015-01-15 18:41 UTC
