### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by valix** [AtomLinter/Linter#345] opened 2015-01-16 08:39 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
StatusBarSummaryView.render (/home/valix/SSD/atom/packages/linter/lib/statusbar-summary-view.coffee:11:21)
```

**Comment by dmnd** [comment] 2015-01-16 08:39
Dupe of #343

**Closed by dmnd** 2015-01-16 08:39 UTC
