### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by stramel** [AtomLinter/Linter#434] opened 2015-02-18 20:41 UTC
1. Open a new file (`ctrl+n`)
2. Paste `localStorage.clear();sessionStorage.clear();sessionStorage['currentLocation']=JSON.stringify({latitude:30, longitude:-105});location.reload();`
3. Open command palette (`ctrl+shift+P`)
4. type "grammar"
5. press `enter`

**Atom Version**: 0.181.0-a14f1ab
**System**: linux 3.13.0-45-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.11.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/stramel/.atom/packages/linter-jscs/lib/linter-jscs.coffee:37

TypeError: Cannot read property 'split' of undefined
  at new LinterJscs (/home/stramel/.atom/packages/linter-jscs/lib/linter-jscs.coffee:37:16)
  at LinterView.initLinters (/home/stramel/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at /home/stramel/.atom/packages/linter/lib/linter-view.coffee:100:8
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.handleGrammarChange (/usr/local/share/atom/resources/app/src/text-editor.js:2810:27)
  at /usr/local/share/atom/resources/app/src/text-editor.js:199:24
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/usr/local/share/atom/resources/app/src/tokenized-buffer.js:168:27)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/usr/local/share/atom/resources/app/src/display-buffer.js:1058:35)
  at TextEditor.module.exports.TextEditor.setGrammar (/usr/local/share/atom/resources/app/src/text-editor.js:2415:33)
  at GrammarListView.module.exports.GrammarListView.confirmed (/usr/local/share/atom/resources/app/node_modules/grammar-selector/lib/grammar-list-view.js:60:21)
  at GrammarListView.module.exports.SelectListView.confirmSelection (/usr/local/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/local/share/atom/resources/app/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/local/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/local/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/local/share/atom/resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -0:06.0 application:new-file (atom-text-editor.editor)
     -0:05.4 core:paste (atom-text-editor.editor)
     -0:03.8 command-palette:toggle (atom-text-editor.editor)
     -0:02.2 core:confirm (atom-text-editor.editor.mini)
     -0:02.2 grammar-selector:show (atom-text-editor.editor)
     -0:00.7 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.5 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/home/stramel/Projects",
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-gjslint"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "linter": {
    "statusBar": "Show error of the selected line",
    "showInfoMessages": true,
    "showErrorInline": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
atom-jasmine, v0.5.0
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
autocomplete-snippets, v1.0.1
editorconfig, v0.3.0
file-icons, v1.4.11
highlight-line, v0.9.3
highlight-selected, v0.9.0
linter, v0.11.1
linter-jscs, v1.6.0
linter-jshint, v0.1.0
linter-less, v0.3.1
monokai, v0.12.0
pain-split, v1.3.1
project-manager, v1.15.5
project-palette-finder, v2.4.15

# Dev
No dev packages
```

**Comment by niallobrien** [comment] 2015-02-27 21:20
Same here.

**Comment by sirianni** [comment] 2015-03-06 17:45
+1

**Comment by papayasoft** [comment] 2015-03-09 13:14
+1

**Comment by iam4x** [comment] 2015-03-09 13:31
This is for @AtomLinter/linter-jscs I'll check the issue. Thank's for reporting.

**Comment by iam4x** [comment] 2015-03-09 13:41
Should be fixed now :+1:

Mention me here or on the @AtomLinter/linter-jscs repo if other issues with `linter-jscs`

**Closed by iam4x** 2015-03-09 13:41 UTC

**Comment by stramel** [comment] 2015-03-09 13:43
@iam4x :+1: Thank you!

**Comment by papayasoft** [comment] 2015-03-09 14:18
@iam4x Many thanks!

**Comment by rzlourenco** [comment] 2015-08-04 08:35
I'm also getting this error. Steps to reproduce:

1. Create new file
2. Set file as Haskell
3. Save file

**Atom Version**: 1.0.3
**System**: linux 4.1.3-1-ARCH
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.0


### Stack Trace

Uncaught TypeError: Cannot read property 'split' of undefined

```
At /home/rzl/.atom/packages/linter/lib/views/message.coffee:53

TypeError: Cannot read property 'split' of undefined
  at Function.Message.processMultiLine (/home/rzl/.atom/packages/linter/lib/views/message.coffee:53:5)
  at Function.Message.renderMessage (/home/rzl/.atom/packages/linter/lib/views/message.coffee:46:30)
  at linter-message.Message.attachedCallback (/home/rzl/.atom/packages/linter/lib/views/message.coffee:6:26)
  at linter-panel.<anonymous> (/home/rzl/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/home/rzl/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
  at LinterViews.renderPanelMessages (/home/rzl/.atom/packages/linter/lib/linter-views.coffee:107:12)
  at LinterViews.render (/home/rzl/.atom/packages/linter/lib/linter-views.coffee:42:6)
  at /home/rzl/.atom/packages/linter/lib/linter-plus.coffee:29:14
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/home/rzl/.atom/packages/linter/lib/message-registry.coffee:55:16)
  at /home/rzl/.atom/packages/linter/lib/message-registry.coffee:57:31

```

### Commands

```
     -0:55 core:delete (atom-text-editor.editor.is-focused)
     -0:54.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:54.7.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
     -0:54.7.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:54.7.0 ide-haskell:lint-file (atom-text-editor.editor.is-focused)
     -0:54.7.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "autocomplete-snippets",
      "snippets"
    ]
  },
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.5
ide-haskell, v0.6.2
language-haskell, v1.2.1
linter, v1.3.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-08-04 08:37
@lierdakil the message is coming from your package buddy. https://github.com/atom-community/linter/blob/master/lib/views/message.coffee#L53

**Comment by lierdakil** [comment] 2015-08-04 13:51
@steelbrain, what the hell? Why does `processMultiline` accept `text` argument, but on line 53 it's suddenly `@text`?

**Comment by lierdakil** [comment] 2015-08-04 13:53
Oh, I see. Because you copied code without removing `@` in https://github.com/atom-community/linter/commit/23ad514b3fecc3d5e36f64b30ade8a16c9092d0e

**Comment by steelbrain** [comment] 2015-08-04 15:49
Ouch :stuck_out_tongue:
