### ISSUE TITLE
Keymap is gone

### ISSUE THREAD

**Issue by brunobord** [AtomLinter/Linter#597] opened 2015-06-24 09:44 UTC
Looks like the very convenient keyboard shortcuts to jump from one "marked as error or warning line" to another are gone, now.

Would it be possible to have them available again, please?

**Comment by iam4x** [comment] 2015-06-24 11:19
@brunobord There's a command called `Linter: Next Error` accessible from command palette.

**Comment by steelbrain** [comment] 2015-06-24 12:28
Closing as answered

**Comment by iam4x** [comment] 2015-06-24 13:03
@steelbrain The issue is not closed, @brunobord is asking for a keyboard shortcut to this command. I agree with the need to add one.

I don't know where shortcut are put, someone could resolve this?

**Comment by steelbrain** [comment] 2015-06-24 13:04
What keyboard shortcut would you suggest? btw, people can do this themselves by modifying their `keymap.cson` and mapping `linter:next-error` to anything they like

**Comment by iam4x** [comment] 2015-06-24 13:10
@steelbrain Okey, I prefere to do not put a default shortcut for it. It can conflict with another package, the best is to add a note on the `README.md` how to configure shortcut to the commands.

I'll add it on my PR #598 which is modifying the commands.

**Comment by AsaAyers** [comment] 2015-06-24 13:49
If Linter@0.x.x had a shortcut I think it would be good to adopt that, or to at least use it as the example of how to add it if you need it.

**Comment by iam4x** [comment] 2015-06-24 13:51
@AsaAyers I've searched code from before, no default shortcut was set.

**Comment by brunobord** [comment] 2015-06-24 14:12
the keymap was defined here: https://github.com/AtomLinter/Linter/blob/d22fb154ae4698a932fffd09649ed4268d25e3f9/keymaps/linter.cson

**Comment by iam4x** [comment] 2015-06-24 14:37
@brunobord Nice catch, didn't found them.

**Closed** 2015-06-26 22:39 UTC
Labels: enhancement, in progress
