### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by paulomcnally** [AtomLinter/Linter#385] opened 2015-01-22 20:38 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJscs.Linter.getNodeExecutablePath (/Users/paulomcnally/.atom/packages/linter/lib/linter.coffee:104:10)
  at LinterJscs.Linter.getCmdAndArgs (/Users/paulomcnally/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJscs.Linter.lintFile (/Users/paulomcnally/.atom/packages/linter/lib/linter.coffee:112:24)
  at /Users/paulomcnally/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/paulomcnally/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-compile-coffee"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
archive-view, v0.40.0
autoclose-html, v0.13.0
autocomplete-plus, v1.0.0
autocomplete-plus-async, v0.22.0
coffee-lint, v0.7.3
color-picker, v1.2.6
jshint, v1.1.3
less-autocompile, v0.3.3
linter, v0.9.0
linter-jscs, v1.4.9
linter-jsonlint, v0.1.2
markdown-preview, v0.112.0
omnisharp-atom, v0.1.6
pretty-json, v0.3.1
run-in-browser, v0.1.1
seti-syntax, v0.2.1
seti-ui, v0.5.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-22 21:08
Closing as dupe of #329 

This is fixed in the latest version, please upgrade!

**Closed by dmnd** 2015-01-22 21:08 UTC

**Comment by paulomcnally** [comment] 2015-01-22 21:20
:+1:
