### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by rykelley** [AtomLinter/Linter#336] opened 2015-01-14 22:39 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJsYaml.Linter.getNodeExecutablePath (/Users/rkelley/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJsYaml.Linter.getCmdAndArgs (/Users/rkelley/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJsYaml.Linter.lintFile (/Users/rkelley/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/rkelley/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/rkelley/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "yosemite-unity-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
linter, v0.9.1
linter-js-yaml, v0.1.3
yosemite-unity-ui, v0.3.13

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-14 22:40
Dupe of #329, please upgrade

**Closed by dmnd** 2015-01-14 22:40 UTC
