### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by ekarlsso** [AtomLinter/Linter#342] opened 2015-01-15 20:04 UTC
[Enter steps to reproduce below:]

Start atom.io

**Atom Version**: 0.173.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJscs.Linter.getNodeExecutablePath (/Users/ekarlsso/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJscs.Linter.getCmdAndArgs (/Users/ekarlsso/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJscs.Linter.lintFile (/Users/ekarlsso/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/ekarlsso/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/ekarlsso/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter": {}
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.2
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
color-picker, v1.2.6
emmet, v2.3.0
file-icons, v1.4.4
js-refactor, v0.3.0
linter, v0.9.1
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
refactor, v0.4.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-15 21:34
Dupe of #329. This is fixed in the latest version; please upgrade!

**Closed by dmnd** 2015-01-15 21:34 UTC

**Comment by ekarlsso** [comment] 2015-01-16 20:40
thanks
