### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by nguasch** [AtomLinter/Linter#339] opened 2015-01-15 11:44 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.172.0
**System**: Mac OS X 10.10.1
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.7.3

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/norbert.guasch/.atom/packages/linter/lib/linter.coffee:99:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/norbert.guasch/.atom/packages/linter/lib/linter.coffee:80:25)
  at LinterJshint.Linter.lintFile (/Users/norbert.guasch/.atom/packages/linter/lib/linter.coffee:107:24)
  at /Users/norbert.guasch/.atom/packages/linter/lib/linter-view.coffee:141:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint"
    ]
  },
  "linter": {
    "showHighlighting": false
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.7.3
linter-csslint, v0.0.11
linter-jshint, v0.1.0
open-last-project, v0.1.1
script, v2.13.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-15 17:51
Dupe of #329, please upgrade.

**Closed by dmnd** 2015-01-15 17:51 UTC
