### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by TomckySan** [AtomLinter/Linter#334] opened 2015-01-13 22:30 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.170.0
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:224

TypeError: Arguments to path.join must be strings
  at f (path.js:224:15)
  at Object.filter (native)
  at Object.exports.join (path.js:229:40)
  at LinterJshint.Linter.getNodeExecutablePath (c:\Users\Tomoka\.atom\packages\linter\lib\linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (c:\Users\Tomoka\.atom\packages\linter\lib\linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (c:\Users\Tomoka\.atom\packages\linter\lib\linter.coffee:122:24)
  at c:\Users\Tomoka\.atom\packages\linter\lib\linter-view.coffee:138:18
  at Array.forEach (native)
  at c:\Users\Tomoka\.atom\packages\linter\lib\linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
docblockr, v0.5.8
file-icons, v1.4.4
linter, v0.9.1
linter-jshint, v0.1.0
linter-php, v0.0.11
script, v2.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-13 22:31
Dupe of #329. Please upgrade to the latest version.

**Closed by dmnd** 2015-01-13 22:31 UTC

**Comment by TomckySan** [comment] 2015-01-13 22:39
Thank you!
