### ISSUE TITLE
Inline tooltip blocks current lines when line wrap is on

### ISSUE THREAD

**Issue by itsnotvalid** [AtomLinter/Linter#613] opened 2015-06-25 08:20 UTC
Version: 1.0.4
When line wrap is enabled, the tooltip is always showing right after the first line, which effectively block the virtual 2nd line (which some linters mostly treat them as the same line)
Probably the tooltip should be shown after the last virtual line.

P.S. if the tooltip could be set to shown at the status bar, it would be the best.

**Comment by steelbrain** [comment] 2015-06-25 13:16
Dupe of https://github.com/AtomLinter/Linter/issues/607 and https://github.com/AtomLinter/Linter/issues/608

**Closed by steelbrain** 2015-06-25 13:16 UTC
Labels: enhancement

**Comment by itsnotvalid** [comment] 2015-06-26 10:51
Thanks. Didn't check.
