### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by nurtext** [AtomLinter/Linter#335] opened 2015-01-14 13:02 UTC
Steps to reproduce:
1. Start Atom and load a file (HTML in my case)

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.9.1

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:390

TypeError: Arguments to path.join must be strings
  at Object.exports.join (path.js:390:15)
  at LinterJshint.Linter.getNodeExecutablePath (/Users/cedric/.atom/packages/linter/lib/linter.coffee:114:10)
  at LinterJshint.Linter.getCmdAndArgs (/Users/cedric/.atom/packages/linter/lib/linter.coffee:90:25)
  at LinterJshint.Linter.lintFile (/Users/cedric/.atom/packages/linter/lib/linter.coffee:122:24)
  at /Users/cedric/.atom/packages/linter/lib/linter-view.coffee:138:18
  at Array.forEach (native)
  at /Users/cedric/.atom/packages/linter/lib/linter-view.coffee:137:18
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "welcome",
      "metrics",
      "feedback",
      "archive-view",
      "open-on-github",
      "package-generator",
      "release-notes",
      "styleguide",
      "autosave",
      "deprecation-cop",
      "linter-csslint",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-dark-ui",
      "specials-board"
    ],
    "audioBeep": false
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
emmet, v2.3.0
file-icons, v1.4.4
linter, v0.9.1
linter-jshint, v0.1.0
linter-php, v0.0.11
specials-board, v0.6.1
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dmnd** [comment] 2015-01-14 21:12
Dupe of #329. This is already fixed. Please upgrade!

**Closed by dmnd** 2015-01-14 21:12 UTC
