### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ScottBouloutian** [AtomLinter/Linter#350] opened 2015-01-16 22:05 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
StatusBarSummaryView.render (/Users/scott/.atom/packages/linter/lib/statusbar-summary-view.coffee:11:21)
```

**Comment by dmnd** [comment] 2015-01-16 22:28
Closing as dupe of #343

**Closed by dmnd** 2015-01-16 22:28 UTC
