### ISSUE TITLE
Linter refreshing/reloading covers code, making programming at the bottom of a file impossible.

### ISSUE THREAD

**Issue by bnb** [AtomLinter/Linter#452] opened 2015-02-28 19:50 UTC
Whenever I type something new at the end of a file that is part of the language I'm linting with, the linter refreshes, disappears, and then reappears. The problem with this is that it moves the code to the bottom of the window, filling up the space the linter was in. When the linter reappears, that area is covered by it. It's _impossible_ to code like that. I have to disable the linter every time I want to write code.

**Comment by dmnd** [comment] 2015-03-07 03:08
Closing as dupe of #90.

@bnb, #90 has a [workaround for this problem](https://github.com/AtomLinter/Linter/issues/90#issuecomment-66370207), so take a look

**Closed by dmnd** 2015-03-07 03:08 UTC
